FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block neutron_mlnx_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.enable_extra_repos(['libvirt']) }}

{% set neutron_mlnx_agent_packages = [
    'python3-libvirt',
    'python3-ethtool',
] %}
{% if base_distro == 'openeuler' %}
    {% set neutron_mlnx_agent_packages = neutron_mlnx_agent_packages + [
        'zeromq-devel',
    ] %}
{% endif %}

{{ macros.install_packages(neutron_mlnx_agent_packages | customizable("packages")) }}

{% set neutron_mlnx_agent_pip_packages = [
    'networking-mlnx',
] %}

{# NOTE(hrw): pyzmq 20 fails to build while 19.* and 21.* build fine. #}
{% set neutron_mlnx_agent_pyzmq_version = "21.*" %}
{% if base_distro == 'openeuler' %}
    {% set neutron_mlnx_agent_pyzmq_version = "25.*" %}
{% endif %}
RUN {{ macros.upper_constraints_version_change("pyzmq", "20.0.0", neutron_mlnx_agent_pyzmq_version) }} \
    && {% if base_distro == 'openeuler' %}ZMQ_PREFIX=/usr {% endif %}{{ macros.install_pip(neutron_mlnx_agent_pip_packages | customizable("pip_packages")) }}

{% block neutron_mlnx_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
