FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block horizon_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='horizon') }}

{% if base_package_type == 'rpm' %}

    {% set horizon_packages = [
        'gettext'
    ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}
{% elif base_package_type == 'deb' %}

    {% set horizon_packages = [
        'gettext',
        'locales',
        'tzdata'
    ] %}

{{ macros.install_packages(horizon_packages | customizable("packages")) }}

{% endif %}

ADD horizon-archive /horizon-source
ADD plugins-archive /

{% set horizon_pip_packages = [
    '/horizon',
    'django_redis'
] %}

{% set horizon_plugins_pip_packages = [
    '/plugins/*'
] %}

{% if base_distro == 'openeuler' %}
    {% set horizon_pip_env = 'PIP_CONSTRAINT=/requirements/upper-constraints.txt PIP_BUILD_CONSTRAINT=/requirements/upper-constraints.txt' %}
    {% set horizon_pip_extra_args = '--find-links /tmp/horizon-xstatic-wheels' %}
    {% set horizon_xstatic_wheel_packages = [
        'XStatic-Angular',
        'XStatic-Angular-Bootstrap',
        'XStatic-Angular-FileUpload',
        'XStatic-Angular-Gettext',
        'XStatic-Angular-lrdragndrop',
        'XStatic-Angular-Schema-Form',
        'XStatic-Bootstrap-Datepicker',
        'XStatic-Bootstrap-SCSS',
        'XStatic-bootswatch',
        'XStatic-D3',
        'XStatic-Hogan',
        'XStatic-Font-Awesome',
        'XStatic-Jasmine',
        'XStatic-jQuery',
        'XStatic-JQuery-Migrate',
        'XStatic-JQuery.quicksearch',
        'XStatic-JQuery.TableSorter',
        'XStatic-jquery-ui',
        'XStatic-JSEncrypt',
        'XStatic-mdi',
        'XStatic-objectpath',
        'XStatic-Rickshaw',
        'XStatic-roboto-fontface',
        'XStatic-smart-table',
        'XStatic-Spin',
        'XStatic-term.js',
        'XStatic-tv4',
        'XStatic-Moment-Timezone',
    ] %}
{% else %}
    {% set horizon_pip_env = '' %}
    {% set horizon_pip_extra_args = '' %}
{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_extend_start

# NOTE(hrw): to install horizon from unpacked sources we cannot have it in upper-constraints.txt
# NOTE(kevko): This dance with local settings python paths below is needed
# because we are using different distros with different python version and we need to
# know to which path symlink should point to.
# NOTE(bbezak): pin setuptools for pip build isolation due to
# https://bugs.launchpad.net/horizon/+bug/2141293
RUN ln -s horizon-source/* horizon \
    && {{ macros.upper_constraints_remove("horizon") }} \
    && echo "setuptools<82" > /tmp/horizon-build-constraints.txt \
    {% if base_distro == 'openeuler' -%}
    && mkdir -p /tmp/horizon-xstatic-wheels \
    && {{ horizon_pip_env }} PIP_BUILD_CONSTRAINT=/tmp/horizon-build-constraints.txt python3 -m pip wheel --no-cache-dir -c /requirements/upper-constraints.txt -w /tmp/horizon-xstatic-wheels {{ horizon_xstatic_wheel_packages | join(' ') }} \
    {% endif -%}
    && PIP_BUILD_CONSTRAINT=/tmp/horizon-build-constraints.txt \
       {{ macros.install_pip(horizon_pip_packages | customizable("pip_packages"), extra_args=horizon_pip_extra_args, env=horizon_pip_env) }} \
    && mkdir -p /etc/openstack-dashboard \
    && cp -r /horizon/openstack_dashboard/conf/* /etc/openstack-dashboard/ \
    && cp /horizon/openstack_dashboard/local/local_settings.py.example /etc/openstack-dashboard/local_settings.py \
    && local_settings=$(python -c 'import os;import openstack_dashboard;settings=os.path.dirname(openstack_dashboard.__file__) + "/local/local_settings.py";print(settings);') \
    && rm -f $local_settings \
    && ln -s /etc/openstack-dashboard/local_settings.py $local_settings \
    && mkdir -p /etc/openstack-dashboard/local_settings.d \
    && local_settings_d=$(python -c 'import os;import openstack_dashboard;settings_d=os.path.dirname(openstack_dashboard.__file__) + "/local/local_settings.d";print(settings_d);') \
    && rm -rf $local_settings_d \
    && ln -s /etc/openstack-dashboard/local_settings.d $local_settings_d \
    && cp /horizon/manage.py /var/lib/kolla/venv/bin/manage.py \
    && if [ "$(ls /plugins)" ]; then \
           {{ macros.install_pip(horizon_plugins_pip_packages, extra_args=horizon_pip_extra_args, env=horizon_pip_env) }}; \
       fi \
    && for locale in  /var/lib/kolla/venv/lib/python3/site-packages/*/locale; do \
           (cd ${locale%/*} && /var/lib/kolla/venv/bin/django-admin compilemessages) \
       done \
    && chmod 644 /usr/local/bin/kolla_extend_start

{{ macros.kolla_patch_sources() }}

{% block horizon_footer %}{% endblock %}
{% block footer %}{% endblock %}
