FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block tgtd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_package_type == 'rpm' %}

{% if base_distro == 'openeuler' %}
    {% set tgtd_packages = ['scsi-target-utils'] %}

{{ macros.install_packages(tgtd_packages | customizable("packages")) }}
RUN sed -i '1 i include /var/lib/cinder/volumes/*' /etc/tgt/targets.conf

{% else %}

RUN echo 'Not available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{% elif base_package_type == 'deb' %}
    {% set tgtd_packages = ['tgt'] %}

{{ macros.install_packages(tgtd_packages | customizable("packages")) }}
RUN sed -i '1 i include /var/lib/cinder/volumes/*' /etc/tgt/targets.conf

{% endif %}

{% block tgtd_footer %}{% endblock %}
{% block footer %}{% endblock %}
